GET http://localhost:8080/mvc-boot/rest/v1/product/all
####

POST http://localhost:8080/mvc-boot/rest/v1/product
Content-Type: application/json

    {
      "title": "New product json",
      "cost": 1000
    }